{% set name = "extract_model" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/extract_model/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ff44774a6f44a00ee291f544addea1a61e3a352278bf0deadb3073ff6d22fce9

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm
  run:
    - cartopy
    - cf_xarray
    - cmocean
    - dask <=2022.05.0
    - matplotlib-base
    - netcdf4
    - numba
    - numpy
    - python >=3.7
    - pytest
    - requests
    - xarray
    - xcmocean
    # - pip:  # install from github to get recent PRs I contributed
    #   - git@github.com:xarray-contrib/cf-xarray.git

test:
  imports:
    - extract_model
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/extract_model
  license: MIT
  license_file: LICENSE.txt
  summary: Facilitates read-in and extraction for ocean model output.
  doc_url: https://extract-model.readthedocs.io/
  dev_url: https://github.com/axiom-data-science/extract_model

extra:
  recipe-maintainers:
    - kthyng
