{% set name = "extract_model" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/extract_model/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8ef2bf38b12cb4cde96a124a1fc238ff0ceb07b61405b551ee96599dfdf0f977

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - cf_xarray
    - netcdf4
    - numpy <1.24
    - python >=3.8
    - requests
    - scikit-learn  # for xoak tree
    - xarray
    - xoak
    # - pip:  # install from github to get recent PRs I contributed
    #   - git@github.com:xarray-contrib/cf-xarray.git

test:
  imports:
    - extract_model
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/extract_model
  license: MIT
  license_file: LICENSE.txt
  summary: Facilitates read-in and extraction for ocean model output.
  doc_url: https://extract-model.readthedocs.io/
  dev_url: https://github.com/axiom-data-science/extract_model

extra:
  recipe-maintainers:
    - kthyng
